// packages/assets/examples/solid-router/src/entry.server.tsx
import { renderImportMap } from "@pitlane/assets";
import { html } from "@remix-run/html-template";
import { generateHydrationScript, renderToStream } from "@solidjs/web";

import { App } from "./app.tsx";
import { assets } from "./assets.ts";
import { Router } from "./router.ts";

const clientEntryKey = "src/entry.client.tsx";

// Solid's lazy() needs the script URL of every lazy module it renders, keyed by
// source path, so the browser can import it before hydrating. Every page is
// registered through `assets({ include })` in `vite.config.ts`, so its script
// entry answers in dev and in a build alike.
const lazyModules = {
    async resolve(key: string) {
        let page = await assets.getScriptEntry(key);
        return { js: [page.href], css: [] };
    },
};

async function handler(request: Request): Promise<Response> {
    let sources = Router.match(request.url).map(match => match.info!.source);
    if (sources.length === 0) return new Response("Not Found", { status: 404 });

    let entry = await assets.getScriptEntry("src/entry.client.tsx");
    let preloads = await assets.getPreloads([clientEntryKey, ...sources]);
    let stylesheets = await assets.getStylesheets([clientEntryKey, ...sources]);

    // Awaiting the stream waits for the lazy route to load and render. Its head
    // output is not collected: it would only repeat the preloads above.
    let body = await renderToStream(() => <App url={request.url} />, { manifest: lazyModules });

    // `html` escapes every interpolated value. The import map, Solid's
    // hydration script, and the rendered app are complete markup, so they go
    // in through `html.raw`. The map precedes every module link and script.
    let document = html`<!doctype html>
        <html lang="en">
            <head>
                <meta charset="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <title>Solid Router with @pitlane/assets</title>
                <link rel="icon" href="data:," />
                ${html.raw`${renderImportMap({ value: entry.importMap })}`}
                ${stylesheets.map(href => html`<link rel="stylesheet" href="${href}" />`)}
                ${preloads.map(href => html`<link rel="modulepreload" href="${href}" />`)}
                ${html.raw`${generateHydrationScript()}`}
                <script type="module" src="${entry.href}"></script>
            </head>
            <body>
                <div id="app">${html.raw`${body}`}</div>
            </body>
        </html>`;
    return new Response(String(document), {
        headers: { "content-type": "text/html; charset=utf-8" },
    });
}

export default { fetch: handler };

// packages/assets/examples/lit-islands/src/entry.server.ts
import type { TemplateResult } from "lit";

import { renderThunked } from "@lit-labs/ssr";
import { collectResult } from "@lit-labs/ssr/lib/render-result.js";
import { renderImportMap } from "@pitlane/assets";
import { createRouter } from "@remix-run/fetch-router";
import { route } from "@remix-run/fetch-router/routes";
import { html } from "@remix-run/html-template";

import { assets } from "./assets.ts";
import { islands } from "./framework/islands.ts";
import "./styles.css";

interface Page {
    title: string;
    content: TemplateResult;
}

interface PageModule {
    source: string;
    load: () => Promise<Page>;
}

let routes = route({ home: "/", about: "/about" });

// Each page names its source key so the resolver can find its stylesheets in
// the server graph. Loading pages lazily gives each one its own CSS file.
let home: PageModule = { source: "src/pages/home.ts", load: () => import("./pages/home.ts") };
let about: PageModule = { source: "src/pages/about.ts", load: () => import("./pages/about.ts") };

async function renderPage({ source, load }: PageModule): Promise<Response> {
    let page = await load();

    // Lit reports every custom element it renders, so only the islands this
    // page actually used load in the browser.
    let rendered = new Set<string>();
    let body = await collectResult(
        renderThunked(page.content, { customElementRendered: tag => rendered.add(tag) }),
    );
    let entries = [...rendered].flatMap(tag => islands[tag] ?? []);
    let preloads = [...new Set(entries.flatMap(entry => entry.preloads))];
    let stylesheets = await assets.getStylesheets(["src/entry.server.ts", source]);
    // Every entry carries the complete client import map, so any one will do.
    let importMap = entries[0]?.importMap ?? { imports: {} };

    // `html` escapes every interpolated href. `renderImportMap` escapes its own
    // output and Lit escapes the values in the body it rendered, so both go in
    // through `html.raw`.
    let document = html`<!doctype html>
        <html lang="en">
            <head>
                <meta charset="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <title>${page.title} · Lit islands</title>
                <link rel="icon" href="data:," />
                ${stylesheets.map(href => html`<link rel="stylesheet" href="${href}" />`)}
                ${html.raw`${renderImportMap({ value: importMap })}`}
                ${preloads.map(href => html`<link rel="modulepreload" href="${href}" />`)}
                ${entries.map(entry => html`<script type="module" src="${entry.href}"></script>`)}
            </head>
            <body>
                <nav>
                    <a href="${routes.home.href()}">Home</a>
                    <a href="${routes.about.href()}">About</a>
                </nav>
                <main>${html.raw`${body}`}</main>
            </body>
        </html>`;
    return new Response(String(document), {
        headers: { "content-type": "text/html; charset=utf-8" },
    });
}

let router = createRouter();
router.map(routes, {
    actions: {
        home: () => renderPage(home),
        about: () => renderPage(about),
    },
});

// `fetchServer()` passes a client address as a second argument, which
// `router.fetch` would read as `RequestInit`, so only the request goes through.
export default {
    fetch: (request: Request) => router.fetch(request),
};
