// packages/assets/examples/lit-islands/src/entry.server.ts
import type { TemplateResult } from "lit";

import { renderThunked } from "@lit-labs/ssr";
import { collectResult } from "@lit-labs/ssr/lib/render-result.js";
import { renderImportMap } from "@pitlane/assets";
import { createRouter } from "@remix-run/fetch-router";
import { route } from "@remix-run/fetch-router/routes";
import { html } from "@remix-run/html-template";

import { assets } from "./assets.ts";
import { islands } from "./framework/islands.ts";
import "./styles.css";

interface Page {
    title: string;
    content: TemplateResult;
}

interface PageModule {
    source: string;
    load: () => Promise<Page>;
}

let routes = route({ home: "/", about: "/about" });

// Each page names its source key so the resolver can find its stylesheets in
// the server graph. Loading pages lazily gives each one its own CSS file.
let home: PageModule = { source: "src/pages/home.ts", load: () => import("./pages/home.ts") };
let about: PageModule = { source: "src/pages/about.ts", load: () => import("./pages/about.ts") };

async function renderPage({ source, load }: PageModule): Promise<Response> {
    let page = await load();

    // Lit reports every custom element it renders, so only the islands this
    // page actually used load in the browser.
    let rendered = new Set<string>();
    let body = await collectResult(
        renderThunked(page.content, { customElementRendered: tag => rendered.add(tag) }),
    );
    let entries = [...rendered].flatMap(tag => islands[tag] ?? []);
    let preloads = [...new Set(entries.flatMap(entry => entry.preloads))];
    let stylesheets = await assets.getStylesheets(["src/entry.server.ts", source]);
    // Every entry carries the complete client import map, so any one will do.
    let importMap = entries[0]?.importMap ?? { imports: {} };

    // `html` escapes every interpolated href. `renderImportMap` escapes its own
    // output and Lit escapes the values in the body it rendered, so both go in
    // through `html.raw`.
    let document = html`<!doctype html>
        <html lang="en">
            <head>
                <meta charset="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <title>${page.title} · Lit islands</title>
                <link rel="icon" href="data:," />
                ${stylesheets.map(href => html`<link rel="stylesheet" href="${href}" />`)}
                ${html.raw`${renderImportMap({ value: importMap })}`}
                ${preloads.map(href => html`<link rel="modulepreload" href="${href}" />`)}
                ${entries.map(entry => html`<script type="module" src="${entry.href}"></script>`)}
            </head>
            <body>
                <nav>
                    <a href="${routes.home.href()}">Home</a>
                    <a href="${routes.about.href()}">About</a>
                </nav>
                <main>${html.raw`${body}`}</main>
            </body>
        </html>`;
    return new Response(String(document), {
        headers: { "content-type": "text/html; charset=utf-8" },
    });
}

let router = createRouter();
router.map(routes, {
    actions: {
        home: () => renderPage(home),
        about: () => renderPage(about),
    },
});

// `fetchServer()` passes a client address as a second argument, which
// `router.fetch` would read as `RequestInit`, so only the request goes through.
export default {
    fetch: (request: Request) => router.fetch(request),
};

// packages/assets/examples/react-router/src/entry.server.tsx
import { renderImportMap } from "@pitlane/assets";
import { html } from "@remix-run/html-template";
import { renderToReadableStream } from "react-dom/server.edge";
import { StaticRouterProvider, createStaticHandler, createStaticRouter } from "react-router";

import { assets } from "./assets.ts";
import { routes } from "./routes.ts";

let { query, dataRoutes } = createStaticHandler(routes);

async function fetch(request: Request): Promise<Response> {
    // Matching happens before rendering, so the head can name the matched routes' assets.
    let context = await query(request);
    if (context instanceof Response) return context;

    let sources = context.matches.flatMap(match => match.route.handle?.source ?? []);
    // A string literal, so the assets plugin registers the module as a browser entry.
    let entry = await assets.getScriptEntry("src/entry.client.tsx");
    let keys = ["src/entry.client.tsx", ...sources];
    let preloads = await assets.getPreloads(keys);
    let stylesheets = await assets.getStylesheets(keys);

    // React renders only the router, streamed into #root at the <!--app-->
    // marker; the document around it is ordinary server HTML. The import map
    // comes first, because the browser ignores a map that arrives after a
    // module starts loading.
    let page = html`<!doctype html>
        <html lang="en">
            <head>
                <meta charset="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <title>React Router with @pitlane/assets</title>
                ${html.raw`${renderImportMap({ value: entry.importMap })}`}
                ${stylesheets.map(href => html`<link rel="stylesheet" href="${href}" />`)}
                ${preloads.map(href => html`<link rel="modulepreload" href="${href}" />`)}
                <script type="module" src="${entry.href}"></script>
            </head>
            <body>
                <div id="root"><!--app--></div>
            </body>
        </html>`;
    let [head, tail] = String(page).split("<!--app-->");

    let body = await renderToReadableStream(
        <StaticRouterProvider router={createStaticRouter(dataRoutes, context)} context={context} />,
        { signal: request.signal },
    );
    return new Response(body.pipeThrough(around(head!, tail!)), {
        status: context.statusCode,
        headers: { "content-type": "text/html; charset=utf-8" },
    });
}

function around(head: string, tail: string): TransformStream<Uint8Array, Uint8Array> {
    let encoder = new TextEncoder();
    return new TransformStream({
        start: controller => controller.enqueue(encoder.encode(head)),
        flush: controller => controller.enqueue(encoder.encode(tail)),
    });
}

export default { fetch };
